<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8871c846-2885-413d-bfbd-a06a5b72a65f</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>
 
	 
	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />

		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.16" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<!-- Logging -->
		<PackageReference Include="NLog.Web.AspNetCore" Version="5.3.11" />

		<!-- Identity & EF Core -->
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />

		<!-- EF Core Tools & SQL Server -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />

		<!-- Swagger/OpenAPI -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />

		<!-- JWT Authentication -->
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0" />

		<!-- AutoMapper -->
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
	  <ProjectReference Include="..\Application\Application.csproj" />
	  <ProjectReference Include="..\Domain\Domain.csproj" />
	  <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	</ItemGroup>

</Project>
